config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :clocked_ins
  resources :users

  post '/users/:id/follow/:following_id', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow/:following_id', to: "users#unfollow", as: "unfollow_user"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :following_id }
  validates :following_id, uniqueness: { scope: :follower_id }
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: %i[ show edit update destroy ]

  # GET /follows or /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1 or /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to follow_url(@follow), notice: "Follow was successfully created." }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1 or /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to follow_url(@follow), notice: "Follow was successfully updated." }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url, notice: "Follow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_params
      params.require(:follow).permit(:follower_id, :following_id)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<div id="<%= dom_id follow %>">
  <p>
    <strong>Follower:</strong>
    <%= follow.follower_id %>
  </p>

  <p>
    <strong>Following:</strong>
    <%= follow.following_id %>
  </p>

</div>

app/views/follows/_form.html.erb
<%= form_with(model: follow) do |form| %>
  <% if follow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
        <% follow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :follower_id, style: "display: block" %>
    <%= form.number_field :follower_id %>
  </div>

  <div>
    <%= form.label :following_id, style: "display: block" %>
    <%= form.number_field :following_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Show this follow", @follow %> |
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Follows</h1>

<div id="follows">
  <% @follows.each do |follow| %>
    <%= render follow %>
    <p>
      <%= link_to "Show this follow", follow %>
    </p>
  <% end %>
</div>

<%= link_to "New follow", new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @follow %>

<div>
  <%= link_to "Edit this follow", edit_follow_path(@follow) %> |
  <%= link_to "Back to follows", follows_path %>

  <%= button_to "Destroy this follow", @follow, method: :delete %>
</div>