config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :clocked_ins
  resources :users

  post '/users/:id/follow/:following_id', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow/:following_id', to: "users#unfollow", as: "unfollow_user"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/clocked_in.rb
class ClockedIn < ApplicationRecord
  include ActionView::Helpers::DateHelper
  before_create :add_start_date
  before_update :set_end_date
  scope :from_previous_week, -> { where("start_date >= ?", 7.days.ago ).order(Arel.sql("(SELECT AGE(start_date, end_date) ASC)")) }

  belongs_to :user

  validates :user_id, presence: true
  validates :user_id, uniqueness: { scope: :end_date, message: "Should end the current time tracking"}, on: :create

  def duration
    self.end_date.nil? ? nil : distance_of_time_in_words(self.start_date, self.end_date)
  end

  private

  def add_start_date
    self.start_date = DateTime.current()
    self.end_date = nil
  end

  def set_end_date
    self.end_date = DateTime.current()
  end
end

app/controllers/clocked_ins_controller.rb
class ClockedInsController < ApplicationController
  before_action :set_clocked_in, only: %i[ show edit destroy ]
  before_action :set_user_clocked_in, only: %i[ update ]
  protect_from_forgery with: :null_session

  # GET /clocked_ins or /clocked_ins.json
  def index
    @clocked_ins = ClockedIn.from_previous_week
  end

  # GET /clocked_ins/1 or /clocked_ins/1.json
  def show
  end

  # GET /clocked_ins/new
  def new
    @clocked_in = ClockedIn.new
  end

  # GET /clocked_ins/1/edit
  def edit
  end

  # POST /clocked_ins or /clocked_ins.json
  def create
    @clocked_in = ClockedIn.new(clocked_in_params)

    respond_to do |format|
      if @clocked_in.save
        format.html { redirect_to clocked_in_url(@clocked_in), notice: "Clocked in was successfully created." }
        format.json { render :show, status: :created, location: @clocked_in }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clocked_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocked_ins/1 or /clocked_ins/1.json
  def update
    respond_to do |format|
      unless @clocked_in.nil?
        if @clocked_in.update(clocked_in_params)
          format.html { redirect_to clocked_in_url(@clocked_in ), notice: "Clocked in was successfully updated." }
          format.json { render :show, status: :ok, location: @clocked_in  }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @clocked_in.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: "Clocked in or user not found.", status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocked_ins/1 or /clocked_ins/1.json
  def destroy
    @clocked_in.destroy

    respond_to do |format|
      format.html { redirect_to clocked_ins_url, notice: "Clocked in was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clocked_in
      @clocked_in = ClockedIn.find(params[:id])
    end

    def set_user_clocked_in
      @clocked_in = ClockedIn.find_by_id_and_user_id(params[:id], clocked_in_params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def clocked_in_params
      params.require(:clocked_in).permit(:start_date, :start_date, :user_id)
    end
end

app/helpers/clocked_ins_helper.rb
module ClockedInsHelper
end

app/views/clocked_ins/_clocked_in.html.erb
<div id="<%= dom_id clocked_in %>">
  <p>
    <strong>Start date:</strong>
    <%= clocked_in.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= clocked_in.end_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= clocked_in.user_id %>
  </p>

</div>

app/views/clocked_ins/_form.html.erb
<%= form_with(model: clocked_in) do |form| %>
  <% if clocked_in.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(clocked_in.errors.count, "error") %> prohibited this clocked_in from being saved:</h2>

      <ul>
        <% clocked_in.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.datetime_field :end_date %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clocked_ins/edit.html.erb
<h1>Editing clocked in</h1>

<%= render "form", clocked_in: @clocked_in %>

<br>

<div>
  <%= link_to "Show this clocked in", @clocked_in %> |
  <%= link_to "Back to clocked ins", clocked_ins_path %>
</div>

app/views/clocked_ins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clocked ins</h1>

<div id="clocked_ins">
  <% @clocked_ins.each do |clocked_in| %>
    <%= render clocked_in %>
    <p>
      <%= link_to "Show this clocked in", clocked_in %>
    </p>
  <% end %>
</div>

<%= link_to "New clocked in", new_clocked_in_path %>

app/views/clocked_ins/new.html.erb
<h1>New clocked in</h1>

<%= render "form", clocked_in: @clocked_in %>

<br>

<div>
  <%= link_to "Back to clocked ins", clocked_ins_path %>
</div>

app/views/clocked_ins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @clocked_in %>

<div>
  <%= link_to "Edit this clocked in", edit_clocked_in_path(@clocked_in) %> |
  <%= link_to "Back to clocked ins", clocked_ins_path %>

  <%= button_to "Destroy this clocked in", @clocked_in, method: :delete %>
</div>